In [117]:
# pip install pandas
# nltk.download('punkt_tab')

In [1]:
import pandas as pd
import numpy as np
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
lemma = WordNetLemmatizer()

In [6]:
df = pd.read_csv("..\Text_Representation\Conunter_TF_IDF\IMDB Dataset.csv")

<>:1: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
<>:1: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
C:\Users\ABDULLAH AL MASUM\AppData\Local\Temp\ipykernel_26548\3050363139.py:1: SyntaxWarning: "\T" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\T"? A raw string is also an option.
  df = pd.read_csv("..\Text_Representation\Conunter_TF_IDF\IMDB Dataset.csv")


In [120]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [121]:
# pip install nltk

In [122]:
import re
import nltk
from nltk.corpus import stopwords

In [123]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to C:\Users\ABDULLAH AL
[nltk_data]     MASUM\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [124]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My Ass Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The Ass",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My Ass Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "STATS": "Your Sex And Age",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    'R' : 'are',
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait",
    "WB": "Welcome Back",
    "WTF": "What The Fuck",
    "WTG": "Way To Go",
    "WUF": "Where Are You From",
    "WYD": "What You Doing",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired"
}


In [125]:
# pip install textblob

In [126]:
def chat_words_process(text):
  new_text = []
  for word in text.split():
    if word.upper() in chat_words:
      new_text.append(chat_words[word.upper()])
    else:
      new_text.append(word)
  
  return " ".join(new_text).lower()


In [127]:

from textblob import TextBlob
def spelling_correction(text):
  textblb = TextBlob(text)
  return textblb.correct().string


In [128]:
def Text_procecess(text):

  text = text.lower()
  text = re.sub(r'<.*?>', " ", text)
  text = re.sub(r"https?://\S+|www\.\S+", " ", text)
  text = re.sub(r'[^\w\s]', '', text)

  # Chat words
  text = chat_words_process(text)

  # Spelling correction (optional, slow)
  # text = spelling_correction(text)

  # Tokenization
  token = word_tokenize(text)

  # Lemmatization
  text = [lemma.lemmatize(w, pos = 'v') for w in token] 

  # Stopword removal
  text = [w for w in text if w not in stop_words] # stop word remove

  return " ".join(text)

In [129]:
sentence = "The children are playing better games and aslo W"
print(Text_procecess(sentence))

children play better game aslo win


In [130]:
sentence = "The children are playing better games"
print(Text_procecess(sentence))

children play better game


In [131]:
df['clean_comment'] = df['review'].apply(Text_procecess)

In [132]:
df.head()

review sentiment  \
0  One of the other reviewers has mentioned that ...  positive   
1  A wonderful little production. <br /><br />The...  positive   
2  I thought this was a wonderful way to spend ti...  positive   
3  Basically there's a family where a little boy ...  negative   
4  Petter Mattei's "Love in the Time of Money" is...  positive   

                                       clean_comment  
0  one reviewers mention watch 1 oz episode youll...  
1  wonderful little production film technique una...  
2  think wonderful way spend tear eye hot summer ...  
3  basically theres family little boy jake think ...  
4  petter matteis love tear eye money visually st...

In [133]:
# pip install scikit-learn

In [134]:
tfidf = TfidfVectorizer(max_features=10000)

In [135]:
X = tfidf.fit_transform(df['clean_comment'])

In [136]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(50000, 10000))

In [137]:

le  = LabelEncoder()

In [138]:
Y = le.fit_transform(df['sentiment'])

In [139]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=.2, random_state= 42)

In [140]:
Log_reg = LogisticRegression()

In [141]:
model = Log_reg.fit(x_train, y_train)

In [142]:
y_pred = model.predict(x_test)

In [143]:
model.score(x_train, y_train)

0.9205

In [144]:
model.score(x_test, y_test)

0.893

In [145]:
accuracy_score(y_pred, y_test)

0.893

In [146]:
confusion_matrix(y_pred, y_test)

array([[4361,  470],
       [ 600, 4569]])

In [147]:
def sentiment(text):
  cleaned = Text_procecess(text)
  vector = tfidf.transform([cleaned]) # TF-IDF wants list
  prediction = model.predict(vector)[0]
  return le.inverse_transform([prediction])[0] # convert 

# LabelEncoder.inverse_transform converts numeric labels predicted by the model back to their original categorical string labels.

In [148]:
sentiment("Worst movie ever")

'negative'

In [149]:
le.classes_

array(['negative', 'positive'], dtype=object)

In [150]:
c = Text_procecess("This movie is amazing")
v = tfidf.transform([c])
p = model.predict(v)

In [151]:
v.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 10000))

In [152]:
p[0]

np.int64(1)

In [153]:
le.inverse_transform([p])[0]

c:\Users\ABDULLAH AL MASUM\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_label.py:161: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


'positive'